name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  publish-all:
    runs-on: macos-12
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.10.0
        with:
          distribution: zulu
          java-version: 11
          
      - name: Cache Gradle
        uses: ./.github/actions/cache-gradle

      - name: Cache Konan
        uses: ./.github/actions/cache-konan

      - name: Publish the macOS artifacts
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          SIGNING_SECRET_KEY: ${{ secrets.SIGNING_SECRET_KEY }}
        run: ./gradlew publishAllPublicationsToSonatypeRepository --no-parallel
