name: Test Apple Targets

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"
      - "reflection/**"

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11

      - name: Test Apple targets
        run: ./gradlew iosX64Test macosX64Test watchosX64Test