name: Test JVM, JS, and Linux

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"
      - "reflection/**"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11

      - name: Test jvm, js(node + browser), linux on Linux
        run: ./gradlew jvmTest jsTest linuxX64Test