name: Test JVM, JS, and Linux

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"
      - "consumer-smoke-test/**"
      - "deep-print-reflection/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - uses: gradle/actions/setup-gradle@v6

      - name: Cache Konan
        uses: ./.github/actions/cache-konan

      - name: Test jvm, js(node + browser), linux on Linux
        run: ./gradlew jvmTest jsTest linuxX64Test